package com.idisfkj.androidapianalysis.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: setting.proto

/**
 * Protobuf type {@code Settings}
 */
public  final class Settings extends
    com.google.protobuf.GeneratedMessageLite<
        Settings, Settings.Builder> implements
    // @@protoc_insertion_point(message_implements:Settings)
    SettingsOrBuilder {
  private Settings() {
    keyName_ = "";
  }
  public static final int KEY_NAME_FIELD_NUMBER = 1;
  private java.lang.String keyName_;
  /**
   * <code>string key_name = 1;</code>
   * @return The keyName.
   */
  @java.lang.Override
  public java.lang.String getKeyName() {
    return keyName_;
  }
  /**
   * <code>string key_name = 1;</code>
   * @return The bytes for keyName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(keyName_);
  }
  /**
   * <code>string key_name = 1;</code>
   * @param value The keyName to set.
   */
  private void setKeyName(
      java.lang.String value) {
    value.getClass();
  
    keyName_ = value;
  }
  /**
   * <code>string key_name = 1;</code>
   */
  private void clearKeyName() {
    
    keyName_ = getDefaultInstance().getKeyName();
  }
  /**
   * <code>string key_name = 1;</code>
   * @param value The bytes for keyName to set.
   */
  private void setKeyNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    keyName_ = value.toStringUtf8();
    
  }

  public static Settings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Settings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Settings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Settings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Settings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Settings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Settings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Settings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Settings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Settings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Settings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Settings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(Settings prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code Settings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Settings, Builder> implements
      // @@protoc_insertion_point(builder_implements:Settings)
      SettingsOrBuilder {
    // Construct using Settings.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string key_name = 1;</code>
     * @return The keyName.
     */
    @java.lang.Override
    public java.lang.String getKeyName() {
      return instance.getKeyName();
    }
    /**
     * <code>string key_name = 1;</code>
     * @return The bytes for keyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyNameBytes() {
      return instance.getKeyNameBytes();
    }
    /**
     * <code>string key_name = 1;</code>
     * @param value The keyName to set.
     * @return This builder for chaining.
     */
    public Builder setKeyName(
        java.lang.String value) {
      copyOnWrite();
      instance.setKeyName(value);
      return this;
    }
    /**
     * <code>string key_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyName() {
      copyOnWrite();
      instance.clearKeyName();
      return this;
    }
    /**
     * <code>string key_name = 1;</code>
     * @param value The bytes for keyName to set.
     * @return This builder for chaining.
     */
    public Builder setKeyNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Settings)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Settings();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "keyName_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<Settings> parser = PARSER;
        if (parser == null) {
          synchronized (Settings.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<Settings>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Settings)
  private static final Settings DEFAULT_INSTANCE;
  static {
    Settings defaultInstance = new Settings();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Settings.class, defaultInstance);
  }

  public static Settings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Settings> PARSER;

  public static com.google.protobuf.Parser<Settings> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

