package com.idisfkj.androidapianalysis.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: setting.proto

public interface SettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Settings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string key_name = 1;</code>
   * @return The keyName.
   */
  java.lang.String getKeyName();
  /**
   * <code>string key_name = 1;</code>
   * @return The bytes for keyName.
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();
}
