package com.idisfkj.androidapianalysis.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: setting.proto

public final class Setting {
  private Setting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
